#!/bin/bash

find . -type f -name 'Nb_*_K_*_alpha_*_koff_*_kon_*_D_*-*.log' | while read -r log_file; do
	
  line_count=$(wc -l < "$log_file")
  if [[ $line_count -gt 1 ]]; then
    Nb=$(echo "$log_file" | sed -E 's/.*Nb_([0-9]+)_K_.*/\1/')
    K=$(echo "$log_file" | sed -E 's/.*_K_([^_]+)_alpha_.*/\1/')
    alpha=$(echo "$log_file" | sed -E 's/.*_alpha_([^_]+)_koff_.*/\1/')
    koff=$(echo "$log_file" | sed -E 's/.*_koff_([^_]+)_kon_.*/\1/')
    kon=$(echo "$log_file" | sed -E 's/.*_kon_([^_]+)_D_.*/\1/')
    D=$(echo "$log_file" | sed -E 's/.*_D_([0-9]+\.[0-9]+)-.*/\1/')

    txt_prefix="Nb_${Nb}_alpha_${alpha}_K_${K}_kon_${kon}_koff_${koff}_D_${D}"
    find . -type f -name "*${txt_prefix}.txt" -exec rm -v {} \;
    rm -v "$log_file"
  fi
done
